package com.pluralsight;

public class Book {

    //declare variables that will track data
    private int id;
    private String isbn;
    private String title;
    private boolean isCheckedOut;
    private String checkedOutTo;

    //create constructor 'Book' to initialize objects when being defined
    public Book(int id, String isbn, String title) {
        //define variables
        this.id = id;
        this.isbn = isbn;
        this.title = title;

        //initialize default
        this.isCheckedOut = false;
        this.checkedOutTo = " ";
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", isbn='" + isbn + '\'' +
                ", title='" + title + '\'' +
                ", isCheckedOut=" + isCheckedOut +
                ", checkoutOutTo='" + checkedOutTo + '\'' +
                '}';
    }

    //getter methods generated by IntelliJ
    public int getID() {
        return id;
    }

    public String getISBN() {
        return isbn;
    }
    public String getTitle() {
        return title;
    }
    public boolean isCheckedOut() {
        return isCheckedOut;
    }

    public String getCheckedOutTo() {
        return checkedOutTo;
    }

    //declare a method to check the status of book
    public void checkOut(String name) {
        this.checkedOutTo = name;
        this.isCheckedOut = true;
    }

    public void checkIn(){
        this.checkedOutTo = "";
        this.isCheckedOut = false;
    }





}
